### PR TITLE
[GH Pages] Set up as a markdown website

### PR DESCRIPTION
**Pull request by kerrtravers**
This sets the site up as a markdown website, adds Github to the list and changes the tab title. The theme is Jekyll cayman.

### CODE REVIEW

**Review by AmazingMech2418 — APPROVED** [review]
This will work. I still don't know why we need social media though...

**Comment by kerrtravers** [comment]
Yeah, Who set up the twitter?

**Comment by radioblahaj** [comment]
Me! I have acces why? PRGTM.
next time, give me a review too, you have

**Comment by radioblahaj** [comment]
oh you dif

**Comment by kerrtravers** [comment]
@redmangospros Could you change the logo?

**Comment by radioblahaj** [comment]
sure, check it out

**Comment by radioblahaj** [comment]
can you create a logo

**Comment by kerrtravers** [comment]
The last tweet said - 

> Waffle like @scratch, a 3D Interface for coding, drag and drop, being more advanced!

it should be -

> Waffle is like @scratch, a 3D Interface for coding, drag and drop, but it is more advanced!

**Comment by kerrtravers** [comment]
and I think we should leave the "more advanced than http://scratch.mit.edu" out of the bio, we are a separate thing and don't want to keep going over the similarities.

**Comment by radioblahaj** [comment]
I will delate and add.okay

**Comment by kerrtravers** [comment]
Perfect 👍

**Comment by radioblahaj** [comment]
:D

**Comment by kerrtravers** [comment]
@redmangospros You also followed a lot of people that have nothing to do with us... (remember this isn't your personal account)

**Comment by radioblahaj** [comment]
It auto followed

**Comment by kerrtravers** [comment]
Ummm, Could you unfollow then...

**Comment by kerrtravers** [comment]
And use the waffle logo and not - 

hyd2fwg0_400x400

**Comment by radioblahaj** [comment]
Better, willchnage logo

**Comment by kerrtravers** [comment]
No, It's all pixelated...

**Comment by kerrtravers** [comment]
and we're not called wafflepro

**Comment by radioblahaj** [comment]
That's the limit. You can have acces to account,

**Comment by radioblahaj** [comment]
Open QUick andtell me to delate

**Comment by kerrtravers** [comment]
loading...

**Comment by radioblahaj** [comment]
Okay. writte their hi

**Comment by radioblahaj** [comment]
Got it?

**Comment by vutondesign** [comment]
yeah

**Pull request merged**
